components:
  - name: ocm.software/ocm-k8s-toolkit/examples/applyset-pruning
    version: "1.0.0"
    provider:
      name: ocm.software
    resources:
      - name: k8s-manifest-resource
        type: blob
        version: "1.0.0"
        input:
          type: file
          path: ./k8s-manifest.yaml
      - name: k8s-manifest-resource-2
        type: blob
        version: "1.0.0"
        input:
          type: file
          path: ./k8s-manifest-2.yaml
