# Test values for CI/CD and local testing
manager:
  replicas: 1
  image:
    repository: ghcr.io/open-component-model/kubernetes/controller
    tag: latest
  concurrency:
    resource: 10
  resolver:
    workerCount: 10
    workerQueueLength: 100
  logging:
    level: "debug"
    development: true

crd:
  enable: true
  keep: true
