matrix:
  - name: Markdown
    aspell:
      lang: en
      ignore-case: true
      mode: markdown
    dictionary:
      wordlists:
        - .github/config/wordlist.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.context:
          context_visible_first: true
          escapes: '\\[\\`~]'
          delimiters:
            # Ignore multiline content between fences (fences can have 3 or more back ticks)
            # ```yaml
            # content
            # ```
            - open: '(?s)^(?P<open> *`{3,}).*$'
              close: '^(?P=open) *$'
            # Ignore text between inline back ticks
            - open: '(?P<open>`+)'
              close: '(?P=open)'
      - pyspelling.filters.markdown:
          markdown_extensions:
            - pymdownx.superfences
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - '**/*.md'
    default_encoding: utf-8
