components:
  - name: ocm.software/ocm-k8s-toolkit/examples/helm-configuration-localization-advanced
    version: "${artifactVersion}"
    provider:
      name: ocm.software
    resources:
      - name: helm-resource
        type: helmChart
        version: "${artifactVersion}"
        access:
          type: ociArtifact
          imageReference: "ghcr.io/stefanprodan/charts/podinfo:6.9.1@sha256:565d310746f1fa4be7f93ba7965bb393153a2d57a15cfe5befc909b790a73f8a"
      - name: image-resource
        type: ociImage
        version: "${artifactVersion}"
        access:
          type: ociRegistry
          imageReference: "ghcr.io/stefanprodan/podinfo:6.9.1@sha256:262578cde928d5c9eba3bce079976444f624c13ed0afb741d90d5423877496cb"
      - name: kro-rgd
        type: blob
        version: "${artifactVersion}"
        input:
          type: file
          path: ./rgd.yaml
      - name: kro-instance
        type: blob
        version: "${artifactVersion}"
        input:
          type: file
          path: ./instance.yaml
