apiVersion: v2
name: sovereign-notes
description: A Helm chart for the sovereign-notes application
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - notes
  - ocm
  - conformance
  - sovereign

sources:
  - https://github.com/open-component-model/open-component-model

maintainers:
  - name: OCM Team
    url: https://github.com/open-component-model

annotations:
  ocm.software/component: "acme.org/sovereign/notes"
  ocm.software/scenario: "sovereign-cloud-conformance"