name: JSON Schema
on:
  push:
    branches:
    - main
    paths:
    - '**/schemas/*.schema.json'
  pull_request:
    branches:
      - main
    paths:
      - '**/schemas/*.schema.json'

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    - name: Setup JSON Schema
      uses: sourcemeta/jsonschema@a6a55d7f3a43487503f52defc19f04ff237a036d # v12.10.1
    - name: Lint JSON Schemas
      run: |
        jsonschema lint $(git ls-files '**/schemas/*.schema.json') \
          --verbose \
          --strict \
          --exclude additional_properties_default \
          --exclude enum_with_type