name: JSON Schema
on:
  push:
    branches:
    - main
    paths:
    - '**/schemas/*.schema.json'
    - '.github/workflows/jsonschema.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**/schemas/*.schema.json'
      - '.github/workflows/jsonschema.yml'

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Setup JSON Schema
      uses: sourcemeta/jsonschema@cfd763b5bf08f819f2ab1667717c14568bd48935 # v13.6.0
    - name: Lint JSON Schemas
      run: |
        jsonschema lint $(git ls-files '**/schemas/*.schema.json') \
          --verbose \
          --exclude additional_properties_default \
          --exclude enum_with_type \
          --exclude description_trailing_period \
          --exclude top_level_examples